#ifndef __RFRX_OPEN_H__
#define __RFRX_OPEN_H__

//frame head
#define FRAME_HEAD_1 0xFF
#define FRAME_HEAD_2 0XFE
#define N_FRAME_HEAD_BIT 15

//RF DATA 
#define FRAME_HEAD_LEN 2
#define FRAME_NUM_LEN 1
#define FRAME_LEN_LEN 1
#define RF_TYPE_LEN 1
#define RF_ID_LEN 3
#define RF_SNR_LEN 4
#define RF_CMD_LEN 1
#define RF_REC_LEN 2
#define RF_CRC_LEN 2
#define RF_MAX_DATA_LEN 2
#define RF_ADD_BYTE_LEN (((FRAME_LEN_LEN+RF_SNR_LEN+RF_TYPE_LEN+RF_ID_LEN+RF_CMD_LEN+RF_MAX_DATA_LEN+RF_REC_LEN+RF_CRC_LEN)\
*N_FRAME_HEAD_BIT/(N_FRAME_HEAD_BIT-1)+2)\
-(FRAME_LEN_LEN+RF_SNR_LEN+RF_TYPE_LEN+RF_ID_LEN+RF_CMD_LEN+RF_MAX_DATA_LEN+RF_REC_LEN+RF_CRC_LEN))

#define FRAME_HEAD_ADDR 0
#define FRAME_NUM_ADDR (FRAME_HEAD_ADDR+FRAME_HEAD_LEN)
#define FRAME_LEN_ADDR (FRAME_NUM_ADDR+FRAME_NUM_LEN)
#define RF_TYPE_ADDR (FRAME_LEN_ADDR+FRAME_LEN_LEN)
#define RF_ID_ADDR (RF_TYPE_ADDR+RF_TYPE_LEN)
#define RF_SNR_ADDR (RF_ID_ADDR+RF_ID_LEN)
#define RF_CMD_ADDR (RF_SNR_ADDR+RF_SNR_LEN)
#define RF_DATA_ADDR (RF_CMD_ADDR+RF_CMD_LEN)
#define RF_REC_ADDR (RF_DATA_ADDR+Datalen)
#define RF_CRC_ADDR (RF_REC_ADDR+RF_REC_LEN)

#define RX_NUM_ADDR 0
#define RX_LEN_ADDR (RX_NUM_ADDR+FRAME_NUM_LEN)
#define RX_TYPE_ADDR (RX_LEN_ADDR+FRAME_LEN_LEN)
#define RX_ID_ADDR (RX_TYPE_ADDR+RF_TYPE_LEN)
#define RX_SNR_ADDR (RX_ID_ADDR+RF_ID_LEN)
#define RX_CMD_ADDR (RX_SNR_ADDR+RF_SNR_LEN)
#define RX_DATA_ADDR (RX_CMD_ADDR+RF_CMD_LEN)
#define RX_REC_ADDR (Temp[RX_LEN_ADDR]+RX_DATA_ADDR-\
(RF_SNR_LEN+RF_TYPE_LEN+RF_ID_LEN+RF_CMD_LEN))
#define RX_CRC_ADDR (RX_REC_ADDR+RF_REC_LEN)

//第一个2是一个码要用两位来表示，第二个2是要保证收到两帧数据
#define MAX_DATA_LEN ((u8)(((FRAME_LEN_LEN+RF_SNR_LEN+RF_TYPE_LEN+RF_ID_LEN+RF_CMD_LEN+RF_REC_LEN+RF_CRC_LEN+RF_MAX_DATA_LEN)\
*N_FRAME_HEAD_BIT/(N_FRAME_HEAD_BIT-1)+FRAME_HEAD_LEN+FRAME_NUM_LEN+1)*2*2))

//常量定义：
#define RX_OK_ODD 1
#define RX_OK_EVEN 0

#define RX_EX_MIN 0x10
#define RX_EX_MAX 0x11
#define RX_BT_1_AND_2 0x12
#define RX_LOW_PWR 0x13

#define RX_NO_FRAME_START 0X20
#define RX_CRC_ERROR 0x21
#define RX_REC_ERROR 0X22

#define EX_MAX_DATA_LEN 0X30

#define MAX_RF_DATA_LEN 19//(FRAME_NUM_LEN+FRAME_LEN_LEN+RF_SNR_LEN+RF_TYPE_LEN
//+RF_ID_LEN+RF_CMD_LEN+RF_MAX_DATA_LEN)

#define MS_MAX_FRAME_TIME 92

//max1473电源
//#define RfPwrOn(); SetBit(PORT_RF_EN, RF_EN);

u8 RfRx(u8 *ptr,u8 n);
u8 RxBit(u8 *Buff);

#endif


